# Site settings
title: PHPDF
description: Grupo de desenvolvedores PHP do Distrito Federal
owner: PHPDF
url: "https://phpdf.org.br"
image: "/images/logo-azul-branco-300x300.png"
baseurl: ""
social:
  twitter: https://twitter.com/phpdf_
  github: https://github.com/php-df
  facebook-official: https://www.facebook.com/groups/518644508178778/
  instagram: https://www.instagram.com/phpdf/
  whatsapp: https://chat.whatsapp.com/invite/AJkY9ZIlCyOJygPb83KMI5
  telegram: https://telegram.me/phpdf
  meetup: https://www.meetup.com/pt-BR/php-df/

# Build settings
markdown: kramdown

# Google-analytics
google-analytics:
  id: ""
